### ISSUE TITLE
[QUESTION]: findByFields with nested fieldName

### ISSUE THREAD

**Issue by simplecommerce** [GraphQLGuide/apollo-datasource-mongodb#69]
Hi,

I am trying to query my DB using `findByFields`.

I am doing the following:

```
this.findByFields({ "contacts._id": _id });
```

My DB structure looks like this:

```
[
  {
    contacts: [
      {
        _id: "some id"
      },
      {
        _id: "some id 2"
      }
    ]
  },
  {
    contacts: [
      {
        _id: "some id 3"
      },
      {
        _id: "some id 4"
      }
    ]
  }
]
```

I was assuming by searching using field "contacts._id" would work but it doesn't seem to work.
When I ouput what `loader` returns for `filter` I get:

```
{ 'contacts._id': { '$in': [ '603ce3183499636b66d6d102' ] } }
```

It seems to transform my value to a string instead of keeping it as an object id.

Not sure if I am doing something wrong?

Any help is appreciated, thanks!

**Comment by lorensr** [comment]
Thanks for reporting, looks like when we loader.load, we should use
EJSON.stringify. PR welcome

**Comment by bitops** [comment]
@lorensr I looked into this a bit but hit a stumbling block. If we use `EJSON.stringify` everywhere blindly it seems to break querying on `ObjectId` type fields. Likely we have to check if fields being queried are of type `ObjectId` and then handle those as a special case. What do you think?

**Comment by lorensr** [comment]
Looks like ejson should support ObjectId? We could add a small test case to check that

https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson-data-types-and-associated-representations

https://www.npmjs.com/package/bson#EJSON

**Comment by lorensr** [comment]
This should be fixed in `0.5.0`. Let me know if it works for you!

https://github.com/GraphQLGuide/apollo-datasource-mongodb/releases/tag/0.5.0

**Comment by bitops** [comment]
@lorensr thanks will do!

**Comment by simplecommerce** [comment]
@lorensr I did a quick test with the latest version and it still doesn't work on my end.

**Comment by bitops** [comment]
@simplecommerce do you have an example test case you can share? I could really use this behavior as well so I'm happy to make another go as I have time.

**Comment by lorensr** [comment]
Added test case and it really should be fixed this time 😄 `0.5.2`

**Comment by simplecommerce** [comment]
@lorensr @bitops ok I just tried it again with the latest update and it works fine now!
I tried different iterations `contacts._id`, `contacts.personId`, etc. Seems to work with no issues.

**Comment by lorensr** [comment]
Great, thanks for testing and for reporting!
